// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model10_2_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 25> locations_array__ =
  {" (found before start of program)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 15, column 2 to column 22)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 19, column 2 to column 16)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 20, column 2 to column 17)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 21, column 2 to column 31)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 22, column 2 to column 11)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 27, column 4 to column 41)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 26, column 2 to line 27, column 41)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 2, column 2 to column 8)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 3, column 2 to column 8)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 4, column 2 to column 8)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 5, column 9 to column 10)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 5, column 11 to column 12)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 5, column 2 to column 16)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 6, column 26 to column 27)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 6, column 2 to column 29)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 10, column 9 to column 10)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 10, column 2 to column 18)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 11, column 2 to column 26)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 15, column 9 to column 10)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 15, column 11 to column 14)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 19, column 9 to column 10)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 19, column 11 to column 12)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 20, column 9 to column 10)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap10/model/model10-2.stan', line 20, column 11 to column 12)"};
class model10_2_model final : public model_base_crtp<model10_2_model> {
 private:
  int N;
  int D;
  int K;
  Eigen::Matrix<double,-1,-1> X_data__;
  std::vector<int> Y;
  Eigen::Matrix<double,-1,1> Zeros_data__;
  int b_raw_2dim__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> Zeros{nullptr, 0};
 public:
  ~model10_2_model() {}
  model10_2_model(stan::io::var_context& context__, unsigned int
                  random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model10_2_model_namespace::model10_2_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 8;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 8;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 9;
      context__.validate_dims("data initialization", "D", "int",
        std::vector<size_t>{});
      D = std::numeric_limits<int>::min();
      current_statement__ = 9;
      D = context__.vals_i("D")[(1 - 1)];
      current_statement__ = 10;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 10;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 11;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 12;
      stan::math::validate_non_negative_index("X", "D", D);
      current_statement__ = 13;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(D)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, D,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), N, D);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 13;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 13;
        pos__ = 1;
        current_statement__ = 13;
        for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
          current_statement__ = 13;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 13;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 13;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 14;
      stan::math::validate_non_negative_index("Y", "N", N);
      current_statement__ = 15;
      context__.validate_dims("data initialization", "Y", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      Y = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 15;
      Y = context__.vals_i("Y");
      current_statement__ = 15;
      stan::math::check_greater_or_equal(function__, "Y", Y, 1);
      current_statement__ = 15;
      stan::math::check_less_or_equal(function__, "Y", Y, K);
      current_statement__ = 16;
      stan::math::validate_non_negative_index("Zeros", "D", D);
      current_statement__ = 17;
      Zeros_data__ = Eigen::Matrix<double,-1,1>::Constant(D,
                       std::numeric_limits<double>::quiet_NaN());
      new (&Zeros)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(Zeros_data__.data(), D);
      current_statement__ = 18;
      stan::model::assign(Zeros, stan::math::rep_vector(0, D),
        "assigning variable Zeros");
      current_statement__ = 19;
      stan::math::validate_non_negative_index("b_raw", "D", D);
      current_statement__ = 20;
      b_raw_2dim__ = std::numeric_limits<int>::min();
      current_statement__ = 20;
      b_raw_2dim__ = (K - 1);
      current_statement__ = 20;
      stan::math::validate_non_negative_index("b_raw", "K - 1", b_raw_2dim__);
      current_statement__ = 21;
      stan::math::validate_non_negative_index("b", "D", D);
      current_statement__ = 22;
      stan::math::validate_non_negative_index("b", "K", K);
      current_statement__ = 23;
      stan::math::validate_non_negative_index("mu", "N", N);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("mu", "K", K);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (D * b_raw_2dim__);
  }
  inline std::string model_name() const final {
    return "model10_2_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --filename-in-msg=model10-2.stan"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model10_2_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,-1> b_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(D, b_raw_2dim__,
          DUMMY_VAR__);
      current_statement__ = 1;
      b_raw = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(D,
                b_raw_2dim__);
      Eigen::Matrix<local_scalar_t__,-1,-1> b =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(D, K, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,-1> mu =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, K, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(b, stan::math::append_col(Zeros, b_raw),
        "assigning variable b");
      current_statement__ = 5;
      stan::model::assign(mu, stan::math::multiply(X, b),
        "assigning variable mu");
      {
        current_statement__ = 7;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 6;
          lp_accum__.add(stan::math::categorical_lpmf<propto__>(
                           stan::model::rvalue(Y, "Y",
                             stan::model::index_uni(n)),
                           stan::math::softmax(
                             stan::math::transpose(
                               stan::model::rvalue(mu, "mu",
                                 stan::model::index_uni(n),
                                 stan::model::index_omni())))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model10_2_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,-1> b_raw =
        Eigen::Matrix<double,-1,-1>::Constant(D, b_raw_2dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      b_raw = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(D,
                b_raw_2dim__);
      Eigen::Matrix<double,-1,-1> b =
        Eigen::Matrix<double,-1,-1>::Constant(D, K,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> mu =
        Eigen::Matrix<double,-1,-1>::Constant(N, K,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(b_raw);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 4;
      stan::model::assign(b, stan::math::append_col(Zeros, b_raw),
        "assigning variable b");
      current_statement__ = 5;
      stan::model::assign(mu, stan::math::multiply(X, b),
        "assigning variable mu");
      if (emit_transformed_parameters__) {
        out__.write(b);
        out__.write(mu);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> b_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(D, b_raw_2dim__,
          DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(b_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(D, b_raw_2dim__),
        "assigning variable b_raw");
      out__.write(b_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "b_raw", "double",
        std::vector<size_t>{static_cast<size_t>(D),
          static_cast<size_t>(b_raw_2dim__)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> b_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(D, b_raw_2dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> b_raw_flat__;
        current_statement__ = 1;
        b_raw_flat__ = context__.vals_r("b_raw");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= b_raw_2dim__; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= D; ++sym2__) {
            current_statement__ = 1;
            stan::model::assign(b_raw, b_raw_flat__[(pos__ - 1)],
              "assigning variable b_raw", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 1;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(b_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"b_raw"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"b", "mu"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(D),
                                                 static_cast<size_t>(
                                                   b_raw_2dim__)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(D),
               static_cast<size_t>(K)},
             std::vector<size_t>{static_cast<size_t>(N),
               static_cast<size_t>(K)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= b_raw_2dim__; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= D; ++sym2__) {
        param_names__.emplace_back(std::string() + "b_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= D; ++sym2__) {
          param_names__.emplace_back(std::string() + "b" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "mu" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= b_raw_2dim__; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= D; ++sym2__) {
        param_names__.emplace_back(std::string() + "b_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= D; ++sym2__) {
          param_names__.emplace_back(std::string() + "b" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "mu" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"b_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(D) + ",\"cols\":" + std::to_string(b_raw_2dim__) + "},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(D) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"b_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(D) + ",\"cols\":" + std::to_string(b_raw_2dim__) + "},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(D) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (D * b_raw_2dim__);
    const size_t num_transformed = emit_transformed_parameters * (((D * K) +
      (N * K)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (D * b_raw_2dim__);
    const size_t num_transformed = emit_transformed_parameters * (((D * K) +
      (N * K)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model10_2_model_namespace::model10_2_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model10_2_model_namespace::profiles__;
}
#endif