// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model12_13_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 28> locations_array__ =
  {" (found before start of program)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 10, column 2 to column 20)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 11, column 2 to column 20)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 12, column 2 to column 17)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 13, column 2 to column 23)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 14, column 2 to column 20)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 20, column 6 to column 65)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 19, column 4 to line 20, column 65)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 18, column 2 to line 20, column 65)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 23, column 6 to column 65)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 22, column 4 to line 23, column 65)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 21, column 2 to line 23, column 65)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 25, column 2 to column 33)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 28, column 6 to column 52)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 27, column 4 to line 28, column 52)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 26, column 2 to line 28, column 52)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 2, column 2 to column 8)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 3, column 2 to column 8)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 4, column 8 to column 9)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 4, column 11 to column 12)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 4, column 2 to column 21)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 5, column 2 to column 8)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 6, column 8 to column 9)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 6, column 10 to column 11)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 6, column 2 to column 39)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 10, column 8 to column 9)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 10, column 10 to column 11)",
  " (in '/Users/sean/Documents/myscript/python-bayes/src/python_bayes/chap12/model/model12-13.stan', line 12, column 9 to column 10)"};
class model12_13_model final : public model_base_crtp<model12_13_model> {
 private:
  int I;
  int J;
  std::vector<std::vector<double>> Y;
  int T;
  std::vector<std::vector<int>> TID;
 public:
  ~model12_13_model() {}
  model12_13_model(stan::io::var_context& context__, unsigned int
                   random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model12_13_model_namespace::model12_13_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 16;
      context__.validate_dims("data initialization", "I", "int",
        std::vector<size_t>{});
      I = std::numeric_limits<int>::min();
      current_statement__ = 16;
      I = context__.vals_i("I")[(1 - 1)];
      current_statement__ = 17;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 17;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 18;
      stan::math::validate_non_negative_index("Y", "I", I);
      current_statement__ = 19;
      stan::math::validate_non_negative_index("Y", "J", J);
      current_statement__ = 20;
      context__.validate_dims("data initialization", "Y", "double",
        std::vector<size_t>{static_cast<size_t>(I), static_cast<size_t>(J)});
      Y = std::vector<std::vector<double>>(I,
            std::vector<double>(J, std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> Y_flat__;
        current_statement__ = 20;
        Y_flat__ = context__.vals_r("Y");
        current_statement__ = 20;
        pos__ = 1;
        current_statement__ = 20;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 20;
          for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
            current_statement__ = 20;
            stan::model::assign(Y, Y_flat__[(pos__ - 1)],
              "assigning variable Y", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 20;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 21;
      context__.validate_dims("data initialization", "T", "int",
        std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      current_statement__ = 21;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 22;
      stan::math::validate_non_negative_index("TID", "I", I);
      current_statement__ = 23;
      stan::math::validate_non_negative_index("TID", "J", J);
      current_statement__ = 24;
      context__.validate_dims("data initialization", "TID", "int",
        std::vector<size_t>{static_cast<size_t>(I), static_cast<size_t>(J)});
      TID = std::vector<std::vector<int>>(I,
              std::vector<int>(J, std::numeric_limits<int>::min()));
      {
        std::vector<int> TID_flat__;
        current_statement__ = 24;
        TID_flat__ = context__.vals_i("TID");
        current_statement__ = 24;
        pos__ = 1;
        current_statement__ = 24;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 24;
          for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
            current_statement__ = 24;
            stan::model::assign(TID, TID_flat__[(pos__ - 1)],
              "assigning variable TID", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 24;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 24;
      stan::math::check_greater_or_equal(function__, "TID", TID, 1);
      current_statement__ = 24;
      stan::math::check_less_or_equal(function__, "TID", TID, T);
      current_statement__ = 25;
      stan::math::validate_non_negative_index("r", "I", I);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("r", "J", J);
      current_statement__ = 27;
      stan::math::validate_non_negative_index("beta", "T", T);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (I * J) + 1 + T + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model12_13_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --filename-in-msg=model12-13.stan"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model12_13_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<std::vector<local_scalar_t__>> r =
        std::vector<std::vector<local_scalar_t__>>(I,
          std::vector<local_scalar_t__>(J, DUMMY_VAR__));
      current_statement__ = 1;
      r = in__.template read<std::vector<std::vector<local_scalar_t__>>>(I,
            J);
      local_scalar_t__ s_r = DUMMY_VAR__;
      current_statement__ = 2;
      s_r = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 3;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(T);
      local_scalar_t__ s_beta = DUMMY_VAR__;
      current_statement__ = 4;
      s_beta = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(0, lp__);
      local_scalar_t__ s_Y = DUMMY_VAR__;
      current_statement__ = 5;
      s_Y = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      {
        current_statement__ = 8;
        for (int i = 1; i <= I; ++i) {
          current_statement__ = 7;
          for (int j = 3; j <= J; ++j) {
            current_statement__ = 6;
            lp_accum__.add(stan::math::normal_lpdf<false>(
                             stan::model::rvalue(r, "r",
                               stan::model::index_uni(i),
                               stan::model::index_uni(j)), ((2 *
                             stan::model::rvalue(r, "r",
                               stan::model::index_uni(i),
                               stan::model::index_uni((j - 1)))) -
                             stan::model::rvalue(r, "r",
                               stan::model::index_uni(i),
                               stan::model::index_uni((j - 2)))), s_r));
          }
        }
        current_statement__ = 11;
        for (int i = 3; i <= I; ++i) {
          current_statement__ = 10;
          for (int j = 1; j <= J; ++j) {
            current_statement__ = 9;
            lp_accum__.add(stan::math::normal_lpdf<false>(
                             stan::model::rvalue(r, "r",
                               stan::model::index_uni(i),
                               stan::model::index_uni(j)), ((2 *
                             stan::model::rvalue(r, "r",
                               stan::model::index_uni((i - 1)),
                               stan::model::index_uni(j))) -
                             stan::model::rvalue(r, "r",
                               stan::model::index_uni((i - 2)),
                               stan::model::index_uni(j))), s_r));
          }
        }
        current_statement__ = 12;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(beta, 6, 0,
                         s_beta));
        current_statement__ = 15;
        for (int i = 1; i <= I; ++i) {
          current_statement__ = 14;
          for (int j = 1; j <= J; ++j) {
            current_statement__ = 13;
            lp_accum__.add(stan::math::normal_lpdf<propto__>(
                             stan::model::rvalue(Y, "Y",
                               stan::model::index_uni(i),
                               stan::model::index_uni(j)),
                             (stan::model::rvalue(r, "r",
                                stan::model::index_uni(i),
                                stan::model::index_uni(j)) +
                             stan::model::rvalue(beta, "beta",
                               stan::model::index_uni(
                                 stan::model::rvalue(TID, "TID",
                                   stan::model::index_uni(i),
                                   stan::model::index_uni(j))))), s_Y));
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model12_13_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<std::vector<double>> r =
        std::vector<std::vector<double>>(I,
          std::vector<double>(J, std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 1;
      r = in__.template read<std::vector<std::vector<local_scalar_t__>>>(I,
            J);
      double s_r = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      s_r = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(T);
      double s_beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      s_beta = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(0, lp__);
      double s_Y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      s_Y = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          out__.write(r[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      out__.write(s_r);
      out__.write(beta);
      out__.write(s_beta);
      out__.write(s_Y);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<std::vector<local_scalar_t__>> r =
        std::vector<std::vector<local_scalar_t__>>(I,
          std::vector<local_scalar_t__>(J, DUMMY_VAR__));
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        current_statement__ = 1;
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          current_statement__ = 1;
          r[(sym2__ - 1)][(sym1__ - 1)] = in__.read<local_scalar_t__>();
        }
      }
      out__.write(r);
      local_scalar_t__ s_r = DUMMY_VAR__;
      current_statement__ = 2;
      s_r = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_r);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(T),
        "assigning variable beta");
      out__.write(beta);
      local_scalar_t__ s_beta = DUMMY_VAR__;
      current_statement__ = 4;
      s_beta = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_beta);
      local_scalar_t__ s_Y = DUMMY_VAR__;
      current_statement__ = 5;
      s_Y = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, s_Y);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "r", "double",
        std::vector<size_t>{static_cast<size_t>(I), static_cast<size_t>(J)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "s_r", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(T)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "s_beta", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "s_Y", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<std::vector<local_scalar_t__>> r =
        std::vector<std::vector<local_scalar_t__>>(I,
          std::vector<local_scalar_t__>(J, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> r_flat__;
        current_statement__ = 1;
        r_flat__ = context__.vals_r("r");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
            current_statement__ = 1;
            stan::model::assign(r, r_flat__[(pos__ - 1)],
              "assigning variable r", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 1;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(r);
      local_scalar_t__ s_r = DUMMY_VAR__;
      current_statement__ = 2;
      s_r = context__.vals_r("s_r")[(1 - 1)];
      out__.write_free_lb(0, s_r);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 3;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta);
      local_scalar_t__ s_beta = DUMMY_VAR__;
      current_statement__ = 4;
      s_beta = context__.vals_r("s_beta")[(1 - 1)];
      out__.write_free_lb(0, s_beta);
      local_scalar_t__ s_Y = DUMMY_VAR__;
      current_statement__ = 5;
      s_Y = context__.vals_r("s_Y")[(1 - 1)];
      out__.write_free_lb(0, s_Y);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"r", "s_r", "beta", "s_beta", "s_Y"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(I),
                                                 static_cast<size_t>(J)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(T)},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
        param_names__.emplace_back(std::string() + "r" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "s_r");
    for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "s_beta");
    param_names__.emplace_back(std::string() + "s_Y");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
        param_names__.emplace_back(std::string() + "r" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "s_r");
    for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "s_beta");
    param_names__.emplace_back(std::string() + "s_Y");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"r\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(I) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(J) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"parameters\"},{\"name\":\"s_r\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"parameters\"},{\"name\":\"s_beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_Y\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"r\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(I) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(J) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"parameters\"},{\"name\":\"s_r\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"parameters\"},{\"name\":\"s_beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s_Y\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((I * J) + 1) + T) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((I * J) + 1) + T) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model12_13_model_namespace::model12_13_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model12_13_model_namespace::profiles__;
}
#endif